config/routes.rb
Customfit::Application.routes.draw do

  resources :gyms

  resources :muscle_groups
  resources :workouts
  resources :workoutexercises
  resources :equipment 
  resources :exercises
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/workout.rb
# == Schema Information
#
# Table name: workouts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  category   :string(255)
#

class Workout < ActiveRecord::Base
  attr_accessible :name, :category, :equipment_ids, :exercises_ids, :muscle_group_ids, :workoutexercises_attributes
  belongs_to  :user
  
  validates   :user_id, presence: true
  validates   :category, presence: true
  
  has_many    :workoutequipments
  has_many    :equipments, :through => :workoutequipments
  
  has_many    :workoutmusclegroups
  has_many    :muscle_groups, :through => :workoutmusclegroups
  
  has_many    :workoutexercises, order: :position
  has_many    :exercises, :through => :workoutexercises, order: :position
  accepts_nested_attributes_for :workoutexercises
  
  default_scope order: 'workouts.created_at DESC'
  
  def add_exercises
    exercise_list = self.arrange_exercises
    exercise_list.each do |exercise|
      self.workoutexercises.create(:exercise_id => exercise.id)
    end
  end
  
  def retrieve_exercises_from_equipment
    self.equipments.map(&:exercises).flatten
  end
      
  def retrieve_exercises_from_muscle_groups
    self.muscle_groups.map(&:exercises).flatten
  end
  
  def filter_exercises
    t = Exercise.arel_table
    exercise_list = self.available_exercises
    filter_keywords = ["Bench Press", "Squat", "Clean", "Deadlift",
                       "Raise", "Lunge", "Good Morning", "Row", "Fly", "Press"]
    filter_keywords.each do |keyword|
      filter_list = exercise_list & Exercise.where(t[:name].matches("%" + keyword))
      exercise_list = exercise_list - filter_list
      filter_list = filter_list.shuffle
      if filter_list.count >= 2
        exercise_list << filter_list[0, 1]
      else
        exercise_list << filter_list
      end
    end
    exercise_list.flatten
  end
  
  def available_exercises
    if self.muscle_groups.count >= 1
      exercise_list = self.retrieve_exercises_from_equipment & self.retrieve_exercises_from_muscle_groups
    else
      exercise_list = self.retrieve_exercises_from_equipment
    end
    exercise_list
  end
  
  def arrange_exercises
    exercise_list = self.filter_exercises
    compound_list = exercise_list & Exercise.where(:exercise_type => "Compound Lift")
    iso_list = exercise_list & Exercise.where(:exercise_type => "Isolation Lift")
    compound_list = compound_list.shuffle
    iso_list = iso_list.shuffle
    workout_list = []
    if (compound_list.count + iso_list.count) >= 12
      if self.category = "Strength Training" 
        workout_list = self.list_builder(compound_list, iso_list)
      elsif self.category = "Hypertrophy Training"
        workout_list = self.list_builder(compound_list, iso_list)
      else
        workout_list = self.list_builder(compound_list, iso_list)
      end
      workout_list = workout_list.flatten.shuffle[0..11]
    else
      workout_list = exercise_list
    end
    workout_list
  end
  
  def list_builder(comp_list, iso_list)
    n = comp_list.count
    m = iso_list.count
    workout_list = []
    unless workout_list.count >= 12 || workout_list.count == (comp_list.count + iso_list.count)
      while n > 0 || m > 0
        if comp_list[n-1]
          workout_list << comp_list[n-1]
        end
        if iso_list[n-1]
          workout_list << iso_list[n-1]
        end
        n = n - 1
        m = m - 1
      end
    end
    workout_list
  end
  
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_filter :admin_user,     only: :index
  before_filter :signed_in_user
  before_filter :correct_workout, only: [:show, :edit, :update, :destroy]
  
  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
    @workout_equipment     = @workout.equipments
    @workout_exercises     = @workout.exercises
    @workout_muscle_groups = @workout.muscle_groups
    @workoutexercises      = @workout.workoutexercises
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = current_user.workouts.build(params[:workout])
    if @workout.save
      flash[:success] = "Workout created!" 
      @workout.add_exercises
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update_attributes(params[:workout])
      redirect_to @workout, :notice  => "Successfully updated workout."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
    redirect_to root_path, :notice => "Successfully destroyed workout."
  end
  
  private
  
    def correct_workout
      @workout = Workout.find(params[:id])
      redirect_to(root_path) unless current_user.id == @workout.user_id
    end
  
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_circuit_training.html.erb
<p><span style="font-size: x-small;">
  <dl class="dl-horizontal">
    <dt>Instructions:</dt> 
    <dd>Each set is meant to be done in an 8 minute interval. Continue through the exercises in the set with minimal breaks and repeat the circuit if necessary.  Between Sets take a 60 - 90 second break before moving on the the next set.  Once you have gone through all three sets, go through them a second time.</dd></dl></span><br /></p>
<table style="border: 1px solid #050404;" border="0" frame="box" class="table table-condensed table-striped table-bordered">
  <tbody>
	<tr class="tablerow1">
	  <td align="left"><span style="font-size: small;">Set1 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span></td>
	  <td align="left"><span style="font-size: small;">Reps &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp;</span></td>
	  <td align="left"><span style="font-size: small;">Exercise Weight</span></td>
    </tr>
	<%= render 'exercise_circuit_row', :n => 0 %>
	<%= render 'exercise_circuit_row', :n => 1 %>
	<%= render 'exercise_circuit_row', :n => 2 %>
	<%= render 'exercise_circuit_row', :n => 3 %>
	<% if @workout_exercises.count >= 8 %>
  	  <tr class="tablerow1">
	    <td align="left"><span style="font-size: small;">Set2</span></td>
	    <td align="left">&nbsp;</td>
	    <td align="left">&nbsp;</td>
	  </tr>
	  <%= render 'exercise_circuit_row', :n => 4 %>
	  <%= render 'exercise_circuit_row', :n => 5 %>
	  <%= render 'exercise_circuit_row', :n => 6 %>        
	  <%= render 'exercise_circuit_row', :n => 7 %>
	<% end %>
	<% if @workout_exercises.count >= 12 %>
	  <tr class="tablerow1">
	    <td align="left"><span style="font-size: small;">Set3</span></td>
	    <td align="left"></td>
	    <td align="left"></td>
	  </tr>
	  <%= render 'exercise_circuit_row', :n => 8 %>
	  <%= render 'exercise_circuit_row', :n => 9 %>
	  <%= render 'exercise_circuit_row', :n => 10 %>
	  <%= render 'exercise_circuit_row', :n => 11 %>
	<% end %>
  </tbody>
</table>

app/views/workouts/_exercise_circuit_row.html.erb
<tr>
  <td align="left"><%= @workout_exercises[n].name %></td>
  <td align="left"><%= @workout_exercises[n].circuit_reps %></td>
  <td align="left"><%= form_for @workoutexercises[n], :remote => true do |f| %>
                     <div class="input-append"><%= f.text_field :exercise_weight, :class => 'submittable input-small' %>
                     <%= button_tag(type: 'submit', class: "btn btn-primary", disable_with: 'Processing...') do %>
                       <i class="icon-ok icon-white"></i>
                     <% end %></div>
                   <% end %>
</tr>

app/views/workouts/_exercise_hypertrophy_row.html.erb
<tr>
  <td align="left"><%= @workout_exercises[n].name %></td>
  <td align="left"><%= @workout_exercises[n].hypertrophy_reps %></td>
  <td align="left"><%= form_for @workoutexercises[n], :remote => true do |f| %>
                     <div class="input-append"><%= f.text_field :exercise_weight, :class => 'input-small' %>
                     <%= button_tag(type: 'submit', class: "btn btn-primary", disable_with: 'Processing...') do %>
                       <i class="icon-ok icon-white"></i>
                     <% end %></div>
                   <% end %>
</tr>

app/views/workouts/_exercise_hypertrophy_row.mobile.erb
<div data-role="collapsible" data-theme="b" data-content-theme="d" data-mini="true">
  <h6>
    <%= @workout_exercises[n].name %>
  </h6>
  <p>
	Reps: <%= @workout_exercises[n].hypertrophy_reps %>
    <%= form_for @workoutexercises[n], :remote => true do |f| %>
      <%= f.label :exercise_weight %>
      <div class="ui-grid-a" >
        <div class="ui-block-a"><%= f.text_field :exercise_weight %></div>
        <div class="ui-block-b"><%= f.submit "Update", "data-role" => "button", "data-theme" => "b" %></div>
      </div>
    <% end %>
  </p>
</div>

app/views/workouts/_form.html.erb
<div class="row">
  <div class="span6">
    <%= semantic_form_for @workout do |f| %>
  	  <%= f.inputs do %>
	    <%= f.input :name %>
		<%= f.input :category, :label => "Type of Workout", :collection => 
		                                                    [["Circuit Training", "Circuit Training"],                               
		                                                     ["Strength Training", "Strength Training"], 
		                                                     ["Hypertrophy Training", "Hypertrophy Training"]] %>
	    <%= f.input :equipments, :label => "Available Equipment" %>
		<%= f.input :muscle_groups, :label => "Muscle Groups To Focus On" %>
      <% end %>
	  <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => { :label => "create case", :class => "btn btn-primary btn-block btn-large", :disable_with => 'Processing...' } %>
   	    <%= f.action :cancel, :as => :link, :button_html => { :label => "create case", :class => "btn btn-block btn-large", :disable_with => 'Processing...' } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/workouts/_hypertrophy_training.mobile.erb
<div data-role="collapsible" data-theme="a" data-content-theme="a">
   <h3>Instructions</h3>
   <p>Add Hypertrophy Training Instructions</p>
</div>
<div class="ui-grid-a">
  <div class="ui-block-a"><strong>Set 1</strong></div>
</div>
<%= render 'exercise_hypertrophy_row', :n => 0 %>
<%= render 'exercise_hypertrophy_row', :n => 1 %>
<%= render 'exercise_hypertrophy_row', :n => 2 %>
<% if @workout_exercises.count >= 6 %>
  <div class="ui-grid-a">
    <div class="ui-block-a"><strong>Set 2</strong></div>
  </div>
  <%= render 'exercise_strength_row', :n => 3 %>
  <%= render 'exercise_strength_row', :n => 4 %>
  <%= render 'exercise_strength_row', :n => 5 %>
<% end %>
<% if @workout_exercises.count >= 9 %>
  <div class="ui-grid-a">
    <div class="ui-block-a"><strong>Set 3</strong></div>
  </div>
  <%= render 'exercise_strength_row', :n => 6 %>
  <%= render 'exercise_strength_row', :n => 7 %>
  <%= render 'exercise_strength_row', :n => 8 %>
<% end %>
<% if @workout_exercises.count >= 12 %>
  <div class="ui-grid-a">
    <div class="ui-block-a"><strong>Set 4</strong></div>
  </div>
  <%= render 'exercise_strength_row', :n => 9 %>
  <%= render 'exercise_strength_row', :n => 10 %>
  <%= render 'exercise_strength_row', :n => 11 %>
<% end %>

app/views/workouts/_strength_training.html.erb
<p><span style="font-size: x-small;">
  <dl class="dl-horizontal">
    <dt>Instructions:</dt> 
    <dd>Perform each set 3 times, alternating the exercises in each set.  Then move to the next set.  In between each exercise take a 15 - 30 second rest.  If Repetitions decrease then increase the weight lifted incrementally.</dd></dl></span><br /></p>
<table style="border: 1px solid #050404;" border="0" frame="box" class="table table-condensed table-striped table-bordered">
  <tbody>
	<tr class="tablerow1">
	  <td align="left"><span style="font-size: small;">Set 1 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span></td>
	  <td align="left"><span style="font-size: small;">Reps &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></td>
	  <td align="left"><span style="font-size: small;">Exercise Weight</span></td>
    </tr>
	<%= render 'exercise_strength_row', :n => 0 %>
	<%= render 'exercise_strength_row', :n => 1 %>
	<tr class="tablerow1">
	  <td align="left"><span style="font-size: small;">Set 2</span></td>
	  <td align="left">&nbsp;</td>
	  <td align="left">&nbsp;</td>
	</tr>
	<%= render 'exercise_strength_row', :n => 2 %>
	<%= render 'exercise_strength_row', :n => 3 %>
	<tr class="tablerow1">
	  <td align="left"><span style="font-size: small;">Set 3</span></td>
	  <td align="left">&nbsp;</td>
	  <td align="left">&nbsp;</td>
	</tr>
	<%= render 'exercise_strength_row', :n => 4 %>
	<%= render 'exercise_strength_row', :n => 5 %>
	<% if @workout_exercises.count >= 8 %>
	  <tr class="tablerow1">
	    <td align="left"><span style="font-size: small;">Set 4</span></td>
	    <td align="left">&nbsp;</td>
	    <td align="left">&nbsp;</td>
	  </tr>
	  <%= render 'exercise_strength_row', :n => 6 %>
	  <%= render 'exercise_strength_row', :n => 7 %>
	<% end %>
	<% if @workout_exercises.count >= 10 %>
	  <tr class="tablerow1">
	    <td align="left"><span style="font-size: small;">Set 5</span></td>
	    <td align="left">&nbsp;</td>
	    <td align="left">&nbsp;</td>
	  </tr>
	  <%= render 'exercise_strength_row', :n => 8 %>
	  <%= render 'exercise_strength_row', :n => 9 %>
	<% end %>
  </tbody>
</table>

app/views/workouts/_workout.html.erb
<li>
  <div class="span3">
    <aside class="span1">
      <% if workout.category == "Circuit Training"%>
        <%= link_to image_tag("weight1.png"), workout %>
      <% elsif workout.category == "Hypertrophy Training" %>
        <%= link_to image_tag("weight2.png"), workout %>
      <% else %>
        <%= link_to image_tag("weight3.png"), workout %>
      <% end %>
    </aside>
    <span class="name">
      <h4><%= workout.category %></span></h4>
    </span>
  </div>
  <aside class="offset4">
	<%= link_to '<i class="icon-eye-open icon-white"></i>'.html_safe, workout, class: "btn btn-primary" %>
	<%= link_to '<i class="icon-trash icon-white"></i>'.html_safe, workout, class: "btn btn-danger", :confirm => "Are you sure?", :method => :delete %>
	</br>
	<span class="timestamp">
      Posted <%= time_ago_in_words(workout.created_at) %> ago.
    </span>
  </aside>
</li>

app/views/workouts/edit.html.erb
<% title "Edit Workout" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @workout %> |
  <%= link_to "View All", workouts_path %>
</p>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for workout in @workouts %>
    <tr>
      <td><%= workout.name %></td>
      <td><%= link_to "Show", workout %></td>
      <td><%= link_to "Edit", edit_workout_path(workout) %></td>
      <td><%= link_to "Destroy", workout, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Workout", new_workout_path %></p>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form' %>

app/views/workouts/new.mobile.erb
<div data-role="header">
  <h1>New Workout</h1>
  <%= link_to "Back", root_path, "data-icon" => "back", "class" => "ui-btn-left" %>
</div>
<div data-role="content">
  <%= semantic_form_for @workout do |f| %>
    <%= f.inputs do %>
      <%= f.input :name %>
      <%= f.input :category, :label => "Type of Workout", :collection => [["Circuit Training", "Circuit Training"], ["Strength Training", "Strength Training"], ["Hypertrophy Training", "Hypertrophy Training"]] %>
      <%= f.input :equipments, :label => "Available Equipment" %>
      <%= f.input :muscle_groups, :label => "Muscle Groups To Focus On" %>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, :as => :button, :button_html => { "data-role" => "button", "data-inline" => "true", "data-theme" => "b", "data-icon" => "check" }%>
    <% end %>
  <% end %>
<div>

app/views/workouts/show.html.erb
<% provide(:title, @workout.name) %>

<div class="row">
  <div class="span8">
    <p>
	  <% if @workout.category == "Strength Training" %>
        <%= render 'strength_training' %>
      <% elsif @workout.category == "Hypertrophy Training" %>
        <%= render 'hypertrophy_training' %>
	  <% else %>
	    <%= render 'circuit_training'%>
	  <% end %>
    </p>
  </div>
</div>

  

app/views/workouts/show.mobile.erb
<div data-role="header">
  <h1><%= @workout.name.capitalize %></h1>
  <%= link_to "Delete", @workout, :confirm => "Are you sure?", :method => :delete, "data-icon" => "delete", "class" => "ui-btn-right" %>
  <%= link_to "Back", current_user, "data-icon" => "back", "class" => "ui-btn-left" %>
</div>
<div data-role="content">
  <% if @workout.category == "Strength Training" %>
    <%= render 'strength_training' %>
  <% elsif @workout.category == "Hypertrophy Training" %>
    <%= render 'hypertrophy_training' %>
  <% else %>
	<%= render 'circuit_training'%>
  <% end %>
</div>