config/routes.rb
Customfit::Application.routes.draw do

  resources :gyms

  resources :muscle_groups
  resources :workouts
  resources :workoutexercises
  resources :equipment 
  resources :exercises
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/equipment.rb
# == Schema Information
#
# Table name: equipment
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Equipment < ActiveRecord::Base
  attr_accessible :name, :exercise_ids, :workout_ids, :gym_ids
  
  validates :name, :presence => true
  
  has_many    :exerciseequipments
  has_many    :exercises, :through => :exerciseequipments
  has_many    :workoutequipments
  has_many    :workouts,  :through => :workoutequipments
  has_many    :gymequipments
  has_many    :gyms,      :through => :gymequipments
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_filter :admin_user

  def index
    @equipment = Equipment.all
  end

  def show
    @equipment = Equipment.find(params[:id])
    @exercises = @equipment.exercises.all
  end

  def new
    @equipment = Equipment.new
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def create
    @equipment = Equipment.new(params[:equipment])

    if @equipment.save
      flash[:success] = "Equipment was successfully created."
      @equipment = Equipment.all
      render "index"
    else
      format.html { render action: "new" }
      format.json { render json: @equipment.errors, status: :unprocessable_entity }
    end
  end

  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    if @equipment.update_attributes(params[:equipment])
      flash[:success] = "Equipment was successfully updated."
      @equipment = Equipment.all
      render "index"
    else
      format.html { render action: "edit" }
      format.json { render json: @equipment.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<div class="row">
  <div class="span6">
    <%= semantic_form_for @equipment do |f| %>
  	  <%= f.inputs do %>
	    <%= f.input :name %>
      <% end %>
      <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => { :label => "create case", :class => "btn btn-large btn-primary btn-block", :disable_with => 'Processing...' } %>
		<br>
    	<%= f.action :cancel, :as => :link, :button_html => { :label => "create case", :class => "btn btn-block btn-large", :disable_with => 'Processing...' } %>
  	  <% end %>
    <% end %>
  </div>
</div>

app/views/equipment/edit.html.erb
<h1>Editing equipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<h1>Equipment</h1>

<table class="table table-condensed">
  <tr>
    <th>Name &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
    <td><%= equipment.name %></td>
    <td><%= link_to 'Show', equipment, class: "btn btn-mini btn-primary" %></td>
    <td><%= link_to 'Edit', edit_equipment_path(equipment), class: "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Equipment', new_equipment_path, class: "btn btn-mini btn-info" %>

app/views/equipment/new.html.erb
<h1>New equipment</h1>

<%= render 'form' %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @equipment.name %>
</p>
<p>
  <b>Exercises:</b>
  <% @exercises.each do |exercise| %>
    <li>
	  <%= exercise.name %>
  	</li>
  <% end %>
</p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>