config/routes.rb
Customfit::Application.routes.draw do

  resources :gyms

  resources :muscle_groups
  resources :workouts
  resources :workoutexercises
  resources :equipment 
  resources :exercises
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/gym.rb
# == Schema Information
#
# Table name: gyms
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  street_address :string(255)
#  city           :string(255)
#  state          :string(255)
#  website        :string(255)
#  hours          :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  latitude       :float
#  longitude      :float
#  phone_number   :string(255)
#  zip            :string(255)
#

class Gym < ActiveRecord::Base
  attr_accessible :name, :street_address, :city, :state, :zip, :phone_number, :website, :hours, :equipment_ids, :latitude, :logintude
  geocoded_by :full_address 
  after_validation :geocode
  
  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :phone_number, presence: true
  validates :website, presence: true
  
  has_many :gymequipments
  has_many :equipments, :through => :gymequipments
  
  def full_address
    [street_address, city, state].compact.join(', ')
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  def index
    @gyms = Gym.near([current_user.latitude, current_user.longitude], 10, :order => :distance).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @gym = Gym.find(params[:id])
  end

  def new
    @gym = Gym.new
  end

  def create
    @gym = Gym.new(params[:gym])
    if @gym.save
      redirect_to @gym, :notice => "Successfully created gym."
    else
      render :action => 'new'
    end
  end

  def edit
    @gym = Gym.find(params[:id])
  end

  def update
    @gym = Gym.find(params[:id])
    if @gym.update_attributes(params[:gym])
      redirect_to @gym, :notice  => "Successfully updated gym."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @gym = Gym.find(params[:id])
    @gym.destroy
    redirect_to gyms_url, :notice => "Successfully destroyed gym."
  end
  
  private
  
  def sort_column
    Gym.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<div class="row">
  <div class="span6">
    <%= semantic_form_for @gym do |f| %>
	  <%= f.inputs do %>
		<%= f.input :name %>
		<%= f.input :street_address %>
		<%= f.input :city %>
		<%= f.input :state %>
		<%= f.input :zip %>
		<%= f.input :phone_number, :required => false %>
		<%= f.input :website, :required => false %>
		<%= f.input :equipments, :label => "Equipment" %>
	  <% end %>
	  <%= f.actions do %>
	    <%= f.action :submit, :as => :button, :button_html => { :label => "create case", :class => "btn btn-primary btn-block btn-large", :disable_with => 'Processing...' } %>
   	    <%= f.action :cancel, :as => :link, :button_html => { :label => "create case", :class => "btn btn-block btn-large", :disable_with => 'Processing...' } %>
	  <% end %>
    <% end %>
  </div>
</div>

app/views/gyms/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @gym %> |
  <%= link_to "View All", gyms_path %>
</p>

app/views/gyms/index.html.erb
<h1>Gyms</h1>

<table class="pretty table">
  <tr>
    <th><%= sortable "name" %></th>
    <th>Full Address</th>
	<th>Distance</th>
    <th><%= sortable "phone_number" %></th>
    <th><%= sortable "website" %></th>
    <th><%= sortable "hours" %></th>
  </tr>
  <% for gym in @gyms %>
    <tr>
      <td><%= gym.name %></td>
      <td><%= gym.full_address %></td>
	  <td><%= gym.distance.to_f.round(2) %> Miles</td>
      <td><%= gym.phone_number %></td>
      <td><%= gym.website %></td>
      <td><%= gym.hours %></td>
      <td><%= link_to "Show", gym %></td>
      <td><%= link_to "Edit", edit_gym_path(gym) %></td>
      <td><%= link_to "Destroy", gym, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Gym", new_gym_path %></p>

app/views/gyms/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", gyms_path %></p>

app/views/gyms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @gym.name %>
</p>
<p>
  <strong>Street Address:</strong>
  <%= @gym.street_address %>
</p>
<p>
  <strong>City:</strong>
  <%= @gym.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @gym.state %>
</p>
<p>
  <strong>Zip:</strong>
  <%= @gym.zip %>
</p>
<p>
  <strong>Phone Number:</strong>
  <%= @gym.phone_number %>
</p>
<p>
  <strong>Website:</strong>
  <%= @gym.website %>
</p>
<p>
  <strong>Hours:</strong>
  <%= @gym.hours %>
</p>

<p>
  <%= link_to "Edit", edit_gym_path(@gym) %> |
  <%= link_to "Destroy", @gym, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", gyms_path %>
</p>