config/routes.rb
Customfit::Application.routes.draw do

  resources :gyms

  resources :muscle_groups
  resources :workouts
  resources :workoutexercises
  resources :equipment 
  resources :exercises
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/muscle_group.rb
# == Schema Information
#
# Table name: muscle_groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class MuscleGroup < ActiveRecord::Base
  attr_accessible :name
  
  has_many :workoutmusclegroups
  has_many :workouts, :through => :workoutmusclegroups
  has_many :exercisemusclegroups
  has_many :exercises, :through => :exercisemusclegroups
end

app/controllers/muscle_groups_controller.rb
class MuscleGroupsController < ApplicationController
  def index
    @muscle_groups = MuscleGroup.all
  end

  def show
    @muscle_group = MuscleGroup.find(params[:id])
  end

  def new
    @muscle_group = MuscleGroup.new
  end

  def create
    @muscle_group = MuscleGroup.new(params[:muscle_group])
    if @muscle_group.save
      redirect_to @muscle_group, :notice => "Successfully created muscle group."
    else
      render :action => 'new'
    end
  end

  def edit
    @muscle_group = MuscleGroup.find(params[:id])
  end

  def update
    @muscle_group = MuscleGroup.find(params[:id])
    if @muscle_group.update_attributes(params[:muscle_group])
      redirect_to @muscle_group, :notice  => "Successfully updated muscle group."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @muscle_group = MuscleGroup.find(params[:id])
    @muscle_group.destroy
    redirect_to muscle_groups_url, :notice => "Successfully destroyed muscle group."
  end
end

app/helpers/muscle_groups_helper.rb
module MuscleGroupsHelper
end

app/views/muscle_groups/_form.html.erb
<div class="row">
  <div class="span6">
    <%= semantic_form_for @muscle_group do |f| %>
  	  <%= f.inputs do %>
	    <%= f.input :name %>
      <% end %>
      <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => { :label => "create case", :class => "btn btn-large btn-primary btn-block", :disable_with => 'Processing...' } %>
		<br>
    	<%= f.action :cancel, :as => :link, :button_html => { :label => "create case", :class => "btn btn-block btn-large", :disable_with => 'Processing...' } %>
  	  <% end %>
    <% end %>
  </div>
</div>

app/views/muscle_groups/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @muscle_group %> |
  <%= link_to "View All", muscle_groups_path %>
</p>

app/views/muscle_groups/index.html.erb
<h1>Muscle Groups</h1>

<table class="table table-condensed">
  <tr>
    <th>Name &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @muscle_groups.each do |muscle_group| %>
  <tr>
    <td><%= muscle_group.name %></td>
    <td><%= link_to 'Show', muscle_group, class: "btn btn-mini btn-primary" %></td>
    <td><%= link_to 'Edit', edit_muscle_group_path(muscle_group), class: "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', muscle_group, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Muscle Group', new_muscle_group_path, class: "btn btn-mini btn-info" %>

app/views/muscle_groups/new.html.erb
<h1>Muscle Groups</h1>

<%= render 'form' %>

<p><%= link_to "Back to List", muscle_groups_path %></p>

app/views/muscle_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @muscle_group.name %>
</p>

<p>
  <%= link_to "Edit", edit_muscle_group_path(@muscle_group) %> |
  <%= link_to "Destroy", @muscle_group, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", muscle_groups_path %>
</p>